# Generated by Django 4.1 on 2022-09-18 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Firm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Firm Name')),
                ('address', models.CharField(max_length=100, verbose_name='Company Address')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ContainerNumber', models.CharField(max_length=5, unique=True, verbose_name='Container Number')),
                ('firm_name', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='invenotry.firm', verbose_name='Firm Name')),
            ],
            options={
                'ordering': ['ContainerNumber'],
            },
        ),
        migrations.CreateModel(
            name='Marka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('markname', models.CharField(max_length=10, verbose_name='Marka Name')),
                ('cartoon', models.IntegerField(verbose_name='Cartoon')),
                ('cbm', models.FloatField(blank=True, null=True, verbose_name='CBM')),
                ('containernumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marka_containernumber', to='invenotry.container', verbose_name='Container Number')),
            ],
            options={
                'unique_together': {('markname', 'cbm', 'cartoon')},
            },
        ),
    ]
