# Generated by Django 4.1 on 2022-09-20 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invenotry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=50, verbose_name='Driver Name')),
                ('driver_number', models.IntegerField(verbose_name='Driver Phone Number')),
                ('driver_vehicle', models.CharField(max_length=50, verbose_name='Driver vehicle number')),
            ],
        ),
        migrations.AddField(
            model_name='marka',
            name='receiveddate',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Stock Received Date'),
        ),
        migrations.CreateModel(
            name='StockSentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent', models.IntegerField(verbose_name='Sent Stocks in Godown')),
                ('remaining', models.IntegerField(verbose_name='Remaining Stocks in Godown')),
                ('sentdate', models.DateTimeField(verbose_name='Stock Sent Date')),
                ('markname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocksentdetail_markname', to='invenotry.marka', verbose_name='Marka')),
                ('total', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocksentdetail_total', to='invenotry.marka', verbose_name='Total Cartoon')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invenotry.vehicle', verbose_name='Vehicle Sent From')),
            ],
        ),
    ]
