# Generated by Django 4.1 on 2022-09-18 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invenotry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Driver name')),
                ('phone_number', models.IntegerField(unique=True, verbose_name='Driver Phone Number')),
                ('vehicle_number', models.CharField(max_length=20, unique=True, verbose_name='Vehicle Number')),
            ],
        ),
        migrations.CreateModel(
            name='Sent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='send.driver', verbose_name='Send Driver')),
                ('lotissuedfrom', models.ManyToManyField(related_name='lotissuedfrom', to='invenotry.marka', verbose_name='Lot Send From')),
                ('marka_name', models.ManyToManyField(max_length=10, to='invenotry.marka', verbose_name='Send Marka')),
                ('sentcartoon', models.ManyToManyField(related_name='sentcartoon', to='invenotry.marka', verbose_name='Sent Cartoon')),
                ('totalcartoon', models.ManyToManyField(related_name='totalcartoon', to='invenotry.marka', verbose_name='Total Cartoon of the lot')),
            ],
        ),
    ]
